package com.prdcv.learnspring.domain;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;

@DynamoDbBean
@DynamoDBTable(tableName = "User")
public class User{
    private String userId;
    private String userName;
    private String userFullName;
    private String userSettingType;
    private String userSettingValue;

    public User(){

    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return userId;
    }

    @DynamoDBAttribute
    public String getUserName() {
        return userName;
    }

    @DynamoDBAttribute
    public String getUserFullName() {
        return userFullName;
    }

    public User setUserId(String userId) {
        this.userId=userId;
        return this;
    }

    public User setUserName(String userName) {
        this.userName=userName;
        return this;

    }
    public User setUserFullName(String userFullName) {
        this.userFullName=userFullName;
        return this;
    }
    @DynamoDBAttribute
    public String getUserSettingValue() {
        return userSettingValue;
    }

    public void setUserSettingValue(String userSettingValue) {
        this.userSettingValue = userSettingValue;
    }
    @DynamoDBAttribute
    public String getUserSettingType() {
        return userSettingType;
    }

    public void setUserSettingType(String userSettingType) {
        this.userSettingType = userSettingType;
    }
}
